.gitignore, CODEOWNERS, Cargo.toml, README.md, coverage_config_x86_64.json, src/i2c/Cargo.toml, src/i2c/README.md, src/i2c/src/cli.yaml, src/i2c/src/i2c.rs, src/i2c/src/main.rs, src/i2c/src/vhu_i2c.rs, src/lib.rs
Hi @andreeaflorescu 
Earlier discussion: https://github.com/rust-vmm/community/issues/106 
I have tried to migrate my existing i2c work over to this repository and did whatever made sense to me (in respect to the workspace thing). There are high chances that I might have made some mistakes here.
I know there would be a lot of things that would require improvement in the i2c code as well as I am really a newbie to the rust world, apologies in advance for reviewing not so great code.
Thanks
=> Add vhost-device I2C support

src/i2c/Cargo.toml
To avoid breaking the crate with a newer version of the
vhost-user-backend crate, fix the dependency to a known good version of
the crate.
=> i2c: Fix dependency to a working commit of backend

.github/dependabot.yaml, .github/dependabot.yml
Remove the incorrect file dependabot.yaml and edit the correct one to
allow crate updates on weekly basis.
=> dependabot: Allow updating crate dependencies automatically

coverage_config_x86_64.json, src/i2c/src/main.rs
Fail early if socket_count is set to 0.
Fixes: #23
=> [i2c] Socket count should be greater than 0

src/i2c/src/vhu_i2c.rs
Removed the unused `mem` field.
=> i2c: Remove unused `mem` field

src/i2c/src/i2c.rs
Use hashmap instead of an array of size 1 << 7, as only a few entries of
the array are used here.
Fixes: #27 
=> [i2c] Use hashmap for device_map

coverage_config_x86_64.json, src/i2c/src/i2c.rs, src/i2c/src/vhu_i2c.rs
Commands like SMBUS Quick don't require a buffer for the request and are
called as zero-length requests. The specification allows such requests
under the VIRTIO_I2C_F_ZERO_LENGTH_REQUEST feature, which is mandatory
to be implemented by the devices now.
Add support for zero-length requests.
The [spec](https://github.com/oasis-tcs/virtio-spec/issues/112) changes are already approved and [linux](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=94e5d5b04f8056f8eec57f8b104ec76d3e945279) code is queued too for upcoming merge window.
=> [i2c] Allow zero-length requests

Cargo.lock, coverage_config_x86_64.json, i2c/Cargo.toml, i2c/src/main.rs
The i2c crate now uses log crate to publish error, info and warn
messages, but doesn't initialize a logger yet and these messages never
make it out.
Initialize the env_logger to see these messages.
=> i2c: Initialize env_logger

README.md
Update README to point to the correct link, replace master with main.
=> vhost-device: Fix broken link

i2c/src/main.rs
If the user passes device list with whitespace before or after, like -l
" 6:32", then " 6".parse::<u32>() fails. Fix this by trimming the
argument for whitespace at start or end.
=> i2c: Trim the device list to avoid errors

gpio/src/gpio.rs, gpio/src/vhu_gpio.rs
get_config() must return only the relevant part of the config, as
requested by the caller, instead of returning entire config structure.
=> gpio: Fix get_config()

gpio/Cargo.toml, i2c/Cargo.toml, rng/Cargo.toml
This allows the use of newer versions of vm-memory and matches with
other crates (e.g. vhost, vhost-user-backend, etc) who also have such a
relaxed vm-memory dependency.
=> build: Relax vm-memory dependency

gpio/src/vhu_gpio.rs
The virtio-gpio driver at the guest performs virtio transaction right
from its probe() routine and without this patch, there is a chance that
the backend may miss the notification from the guest, as the
notification may be sent before the eventfd is set at the backend. This
flag makes the master side wait for reply from backend before proceeding
further for each operation.
=> gpio: Enable REPLY_ACK protocol feature

gpio/src/backend.rs, i2c/src/vhu_i2c.rs, rng/src/main.rs, rng/src/vhu_rng.rs
In preparation to upgrade to Rust version 1.63.0, address clippy
warning demanding that 'Eq' be derived when 'PartialEq' is.
Signed-off-by: Mathieu Poirier <mathieu.poirier@linaro.org>
This PR is needed to address warnings found in [PR#199](https://github.com/rust-vmm/vhost-device/pull/199).
requirements:
test.
=> Preparation for upgrade to Rust version to 1.63.0

gpio/src/backend.rs, i2c/src/i2c.rs, i2c/src/main.rs, i2c/src/vhu_i2c.rs, rng/src/main.rs
see https://doc.rust-lang.org/nightly/edition-guide/rust-2021/prelude.html#details
Signed-off-by: Obei Sideg <obei.sideg@gmail.com>
Remove `use std::convert::TryFrom`
in 2021 edition we won't need to explicitly bring it into scope
see https://doc.rust-lang.org/nightly/edition-guide/rust-2021/prelude.html#details
requirements:
test.
=> Remove `use std::convert::TryFrom`

README.md
In the vhost-user specs [1] we started using better words for the actors involved, so let's do the same here.
[1] https://qemu-project.gitlab.io/qemu/interop/vhost-user.html
Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>
=> README: replace master with frontend

Cargo.lock, crates/vsock/Cargo.toml, crates/vsock/src/main.rs, crates/vsock/src/thread_backend.rs, crates/vsock/src/vhu_vsock.rs, crates/vsock/src/vhu_vsock_thread.rs, crates/vsock/src/vsock_conn.rs
As pointed out in the issue https://github.com/rust-vmm/vhost-device/issues/232, vsock tests fail randomly.
From an initial analysis, it appears that using `--test-threads=1`
never happens, but using a value greater than 1, the tests fails
after a while and almost always with the creation of UDS,
or EpollFD, or on epoll_ctl.
There should be something wrong with FDs when there are multiple
threads running tests (not sure if related to O_CLOEXEC).
This is just a workaround, we will revert this commit when we
identify the root cause.
Marked as draft since it is based on #230, I'll mark it ready when we will merge it.
requirements:
description …
=> Vsock test workaround

LICENSE-BSD-3-Clause, crates/gpio/README.md, crates/gpio/src/backend.rs, crates/gpio/src/gpio.rs, crates/gpio/src/main.rs, crates/gpio/src/vhu_gpio.rs, crates/i2c/README.md, crates/i2c/src/i2c.rs, crates/i2c/src/main.rs, crates/i2c/src/vhu_i2c.rs, crates/rng/README.md, crates/rng/src/main.rs, crates/rng/src/vhu_rng.rs, crates/vsock/README.md
- Fix SPDX headers of gpio, i2c, and rng crates
- Update crates' readme with the licenses
requirements:
test.
=> Set Apache 2.0 OR BSD-3-Clause licenses in all crates

Cargo.lock, crates/gpio/Cargo.toml, crates/i2c/Cargo.toml, crates/rng/Cargo.toml, crates/vsock/Cargo.toml
Switch to caret versions
Specify the dependencies with caret versions.
Fixes: rust-vmm/community#131
=> Caret requirements

crates/i2c/README.md, crates/i2c/src/i2c.rs, crates/i2c/src/main.rs
The GPIO/I2C device names, /dev/gpiochipN or /dev/i2c-N, can change from
one boot to another of the host machine and so aren't stable enough to be
used for bus selection.
Instead start accepting GPIO Controllers label name or I2C bus name as
parameters and parse based on that.
Fixes: https://github.com/rust-vmm/vhost-device/issues/164
=> Replace device numbers with names

Cargo.lock, crates/vsock/Cargo.toml
The 0.2.1 version of virtio-vsock crate contains a [fix](https://github.com/rust-vmm/vm-virtio/pull/207) needed to properly work with the virtio-vsock driver provided by Linux v6.3 and later (originally the new driver was supposed to be in v6.2, but it was postponed).
The fix was just a quick workaround, but in the future more work will be needed in the virtio-vsock crate to not have a Linux-only specific implementation of VsockPacket, as described in [this issue ](https://github.com/rust-vmm/vm-virtio/issues/216).
Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>
requirements:
test.
Release" section of CHANGELOG.md …
=> vsock: require virtio-vsock 0.2.1

Cargo.lock, README.md, coverage_config_x86_64.json, crates/gpio/Cargo.toml, crates/gpio/src/gpio.rs
The upstream version doesn't compile the .c files locally and depends on the package to be locally compiled and installed in advance.
It also doesn't provide pre-generated bindings, and requires bindgen support.
=> gpio: Migrate to the upstream version of libgpiod

Cargo.lock, crates/gpio/Cargo.toml, crates/gpio/src/vhu_gpio.rs, crates/i2c/Cargo.toml, crates/i2c/src/vhu_i2c.rs, crates/rng/Cargo.toml, crates/rng/src/vhu_rng.rs, crates/vsock/Cargo.toml, crates/vsock/src/vhu_vsock.rs
Rather incongruously the common VIRTIO feature flags where part of the net binding. We need to update to using the correct location once the changes:
https://github.com/rust-vmm/vm-virtio/pull/215
get released.
Signed-off-by: Alex Bennée <alex.bennee@linaro.org>
requirements:
- [x ] All commits in this PR are signed (with `git commit -s`), and the commit
- [ x] All added/changed functionality has a corresponding unit/integration
test.
- [x ] All added/changed public-facing functionality has entries in the "Upcoming 
Release" section of CHANGELOG.md (if no such …
=> Updates crates to use virtio_config bindings

crates/vsock/README.md, crates/vsock/src/main.rs, crates/vsock/src/thread_backend.rs, crates/vsock/src/txbuf.rs, crates/vsock/src/vhu_vsock.rs, crates/vsock/src/vhu_vsock_thread.rs, crates/vsock/src/vsock_conn.rs
That buffer is used to store bytes coming from the guest before
sending them to the Unix domain socket. Some use cases might want
to increase or decrease this space, so it would be best to make it
user-customizable. Users can use "--tx-buffer-size=" to configure
TX buffer.
Fixes: https://github.com/rust-vmm/vhost-device/issues/319
requirements:
test.
=> vsock: make TX buffer size configurable

Cargo.lock, crates/vsock/Cargo.toml, crates/vsock/README.md, crates/vsock/src/main.rs, crates/vsock/src/vhu_vsock.rs
Resolve #320 
- Prefer #[arg()] instead of #[clap()] in argument parsing suggested in [clap-rs v4](https://epage.github.io/blog/2022/09/clap4/#more-specific-derive-attributes)
- Use config-rs crate to implement yaml config parsing
- Write tests for new configuration file parsing
Proposed example config file:
```yaml
guest_cid: 4
socket: /tmp/vhost4.socket
uds-path: /tmp/vm4.vsock 
```
``` bash
user@localhost: ./vhost-user-vsock -f config.yaml
```
=> vsock: Implement yaml configuration support

crates/vsock/README.md, crates/vsock/src/main.rs, crates/vsock/src/vhu_vsock.rs
Adds support for instantiating multiple `VhostUserVsockBackend`s parallely to handle multiple guests. Extends the CLI interface to accept the config for multiple VMs in addition to the yaml config file with the `--vm` argument as follows:
```bash
vhost-user-vsock \
--vm guest_cid=3,socket=/tmp/vhost3.socket,uds_path=/tmp/vm3.vsock \ 
--vm guest_cid=4,socket=/tmp/vhost4.socket,uds_path=/tmp/vm4.vsock
```
=> vsock: Add support for multiple guests

crates/vsock/README.md, crates/vsock/src/main.rs, crates/vsock/src/thread_backend.rs, crates/vsock/src/vhu_vsock.rs, crates/vsock/src/vhu_vsock_thread.rs
Adds support for communication between sibling VMs that use the vhost-user-vsock devices from the same vhost-user-vsock application.
=> vsock: Implement sibling VM communication

crates/gpio/LICENSE-APACHE, crates/gpio/LICENSE-BSD-3-Clause, crates/i2c/LICENSE-APACHE, crates/i2c/LICENSE-BSD-3-Clause, crates/rng/LICENSE-APACHE, crates/rng/LICENSE-BSD-3-Clause, crates/scsi/LICENSE-APACHE, crates/scsi/LICENSE-BSD-3-Clause, crates/vsock/LICENSE-APACHE, crates/vsock/LICENSE-BSD-3-Clause
Once we publish crates to crates.io, only the crate subfolder is uploaded. Symlink the license files in in order to include them during packaging.
`cargo package` will replace the symlinks with the actual files during packaging, so crates.io will include the license file.
requirements:
test.
=> Symlink license files into crate folders

Cargo.lock, README.md, crates/gpio/Cargo.toml, crates/i2c/Cargo.toml, crates/rng/Cargo.toml, crates/scsi/Cargo.toml, crates/vsock/Cargo.toml
Various rust-vmm dependencies now support Xen platforms under a new feature `xen`. Add the same here for all the crates.
Also enable the XEN_MMAP protocol feature to use the backends on Xen.
=> Add support for Xen builds

crates/vsock/src/vsock_conn.rs
earlier we were sending credit update messages to guest everytime data was read, now we only send it only if available space is less than which is TX_BUFF_SIZE / 4.
Signed-off-by: Ramyak Mehra <rmehra_be19@thapar.edu>
Fixes #317 
requirements:
test.
=> reduce credit update messages sent to guest

Cargo.lock, crates/vsock/Cargo.toml, crates/vsock/src/main.rs, crates/vsock/src/thread_backend.rs, crates/vsock/src/vhu_vsock.rs, crates/vsock/src/vhu_vsock_thread.rs, crates/vsock/src/vsock_conn.rs
vsock tests could not be run in parallel because of seemingly unrelated crashes, as reported in #232. This PR fixes the bug and also adds a dev dependency to `tempfile` and creates a unique working directory for every test that was previously serialized.
Fixes #232.
requirements:
test.
=> vsock: fix use-after-close RawFd unsafe {} use

crates/gpio/src/backend.rs, crates/i2c/src/main.rs, crates/rng/src/main.rs, crates/scsi/src/main.rs, crates/vsock/src/main.rs
The vhost_user::Error::Disconnected error code is returned by the daemon if the VM is shutting down. Don't Warn the user in this case but just point out that VM may be shutting down.
=> crates: Don't warn for vhost_user::Error::Disconnected

crates/vsock/src/main.rs, crates/vsock/src/thread_backend.rs, crates/vsock/src/vhu_vsock.rs, crates/vsock/src/vhu_vsock_thread.rs
This PR attempts to resolve issues with sibling VM communication described in #384.
Resolves partially  #384.
=> vsock: Fix issues with sibling VM communication

README.md
When we merged the SCSI device, we forgot to put it in the workspace README.md and put the link to the device README.md.
=> README: add reference to the scsi device

crates/vsock/src/thread_backend.rs
VsockConnection::stream which is cloned is always used for
epoll_register, except add_new_guest_conn. Only in add_new_guest_conn,
the original stream is used.
Because a stream's raw fd is used for the key of listener_map, it cannot
find proper listener after the first packet.
Fixes #407
=> vsock: always epoll_register with cloned stream fd

crates/vsock/src/vhu_vsock.rs
In virtio standard, vsock uses 3 vqs(https://docs.oasis-open.org/virtio/virtio/v1.2/csd01/virtio-v1.2-csd01.html#x1-4380002), and crosvm and qemu also uses 3 queues, but this vhost-user-vsock device implementation assumes that there are only 2 vqs, and it causes the problem with crosvm. (at least)
Fixes #408
=> vsock: Increase NUM_QUEUES to 3

Cargo.lock
vhost-user-backend v0.10.0 introduced an issue that affects all vhost-user backends. I easily reproduced the problem with vhost-device-vsock: just restart the guest kernel and the device no longer works.
vhost-user-backend v0.10.1 includes the fix [1] for that issue.
[1] https://github.com/rust-vmm/vhost/pull/180
=> Update vhost-user-backend package dependency

Cargo.lock, Cargo.toml, coverage_config_x86_64.json, crates/scmi/CHANGELOG.md, crates/scmi/Cargo.toml, crates/scmi/LICENSE-APACHE, crates/scmi/LICENSE-BSD-3-Clause, crates/scmi/README.md, crates/scmi/kernel/iio-dummy/.gitignore, crates/scmi/kernel/iio-dummy/Makefile, crates/scmi/kernel/iio-dummy/README.md, crates/scmi/kernel/iio-dummy/iio-dummy-fix.patch, crates/scmi/kernel/iio-dummy/iio_modified_dummy.c, crates/scmi/kernel/iio-dummy/iio_modified_dummy.h, crates/scmi/src/devices.rs, crates/scmi/src/devices/common.rs, crates/scmi/src/devices/fake.rs, crates/scmi/src/devices/iio.rs, crates/scmi/src/devices/mod.rs, crates/scmi/src/main.rs, crates/scmi/src/scmi.rs, crates/scmi/src/vhu_scmi.rs
This PR proposes to add an SCMI (System Control and Management Interface) vhost-user daemon.
SCMI vhost-user device support was added to QEMU and will be available in QEMU 8.1. This patch provides a corresponding vhost-user daemon. It implements the mandatory parts of the Base and Sensor management SCMI protocols. For the Sensor management protocol, SCMI bindings to selected parts of Linux industrial I/O (IIO) sysfs interface are implemented; a fake sensor device for testing is additionally implemented in vhost-user-scmi directly. Additionally, some instructions and patches regarding Linux kernel and its IIO dummy driver are provided in `kernel` subdirectory; these are not part of the functionality but can be useful as a related documentation and for testing.
I understand the PR is quite …
=> Add scmi-vhost-user

Cargo.lock
This should hopefully stop cargo audit complaining about our old version.
=> build(deps): bump vm-memory to 0.12.2

coverage_config_x86_64.json, crates/gpio/src/gpio.rs
We cannot fix the clippy warning before bumping since the old tools do not know the warning. Thus this first picks the submodule bumping commit from the now obsolete #435 PR.
requirements:
test.
=> deps: bump rust-vmm-ci + silence new clippy warning

crates/vsock/src/vhu_vsock.rs, crates/vsock/src/vhu_vsock_thread.rs
Currently, while updating the `cid_map`, it is not checked if the map already contained a key with the same CID before. So, fail to create the vsock thread if the CID is already in use.
Fixes #432.
=> vsock: Don't allow duplicate CIDs

Cargo.lock, crates/vsock/Cargo.toml, crates/vsock/src/vhu_vsock.rs, crates/vsock/src/vhu_vsock_thread.rs
For now, VhostUserVsockThread uses thread pool executor from futures, but it doesn't need to use thread pool executor and futures because we just need background worker thread, and a way to let it work.
So I removed unnecessary external dependency and made the logic simpler by using just thread and channel
requirements:
- [ V ] All commits in this PR are signed (with `git commit -s`), and the commit
- [ V ] All added/changed functionality has a corresponding unit/integration
test.
- [ V ] All added/changed public-facing functionality has entries in the "Upcoming 
Release" section of CHANGELOG.md (if no such section exists, …
=> [vsock] refactor VhostUserVsockThread worker

.github/dependabot.yml
This should group updates into a single PR. Hopefully, that simplfies updates.
Updates that do _actually_ require code changes, will need a separate PR anyway, after which dependabot can be asked to rebase/recreate.
Suggested-by: Patrick Roy <roypat@amazon.co.uk>
Suggested-by: Stefano Garzarella <sgarzare@redhat.com>
requirements:
test.
=> dependabot: enable update grouping

.buildkite/custom-tests.json, staging/coverage_config_x86_64.json
Let's use custom pipelines to run CI tests in the nested worskpace.
We have included all the tests we usually run in the main workspace (rust-vmm-ci/.buildkite/test_description.json), except for "commit-format" which also covers commits for staging crates.
Let's add a `staging\coverage_config_x86_64.json` for testing coverage of crates in staging.
All staging tests have `soft_fail = true` to prevent failures in staging from affecting the CI of the main workspace.
Closes #478
requirements:
test.
=> staging: add custom pipelines to run CI tests

README.md, staging/Cargo.lock, staging/Cargo.toml, staging/vhost-device-video/CHANGELOG.md, staging/vhost-device-video/Cargo.toml, staging/vhost-device-video/LICENSE-APACHE, staging/vhost-device-video/LICENSE-BSD-3-Clause, staging/vhost-device-video/README.md, staging/vhost-device-video/rustfmt.toml, staging/vhost-device-video/src/main.rs, staging/vhost-device-video/src/stream.rs, staging/vhost-device-video/src/vhu_video.rs, staging/vhost-device-video/src/vhu_video_thread.rs, staging/vhost-device-video/src/video.rs, staging/vhost-device-video/src/video_backends.rs, staging/vhost-device-video/src/video_backends/null.rs, staging/vhost-device-video/src/video_backends/v4l2_decoder.rs
This PR adds an experimental virtio-video vhost-user backend, that support v4l2 decoding.
The virtio specification concerning virtio-video is still being discussed. As such, this device should be considered as `experimental`. It is based in the [v3](http://archive.lwn.net:8080/linux-media/6557912.4vTCxPXJkl@os-lin-dmo/T/) patch of the specification, as it has its driver working, and even included in some
out-of-tree kernels (e.g. [chromeos](https://chromium.googlesource.com/chromiumos/third_party/kernel/+/refs/heads/chromeos-5.4/drivers/media/virtio/) and [AAOS](https://github.com/OpenSynergy/android-kernel-common/tree/opsy/android11-5.4-trout/drivers/media/virtio)). This version of the specification patch was also used for the experimental support of virtio-video in …
=> Add experimental vhost-user-video backend

staging/coverage_config_x86_64.json
Update staging coverage target value to current mainline value:
```
FAILED ../rust-vmm-ci/integration_tests/test_coverage.py::test_coverage - ValueError: Current code coverage (57.35%) deviates by -6.92% from the previous code coverage 50.43%.Current ...
```
Found in https://github.com/rust-vmm/vhost-device/pull/496.
requirements:
test.
=> staging: update coverage target

staging/vhost-device-sound/src/audio_backends/pipewire.rs, staging/vhost-device-sound/src/device.rs, staging/vhost-device-sound/src/stream.rs
Tests were not updated with changes in previous commits, so update them.
See https://github.com/rust-vmm/vhost-device/pull/493#issuecomment-1776956302
=> sound: fix broken tests

vhost-device-vsock/src/main.rs, vhost-device-vsock/src/vhu_vsock_thread.rs
We have the following circular references found by Li Zebin:
VhostUserBackend ==> VhostUserVsockThread ==> VringEpollHandler
In addition to causing a resource leak, this causes also an error after we merged commit 38caab2 ("vsock: Don't allow duplicate CIDs"). When the VM reboot or shutdown, the application exits with the following error:
[ERROR vhost_device_vsock] Could not create backend:
CID already in use by another vsock device
This happened because we have these circular references and VhostUserVsockThread::drop() is never invoked. So, we don't remove the cid from the map.
Let's fix this problem by simply removing the reference to VringEpollHandler from VhostUserVsockThread. In fact, we do not need to keep the reference for the lifetime of VhostUserVsockThread, as we only need to …
=> vsock: avoid circular references

vhost-device-vsock/src/vsock_conn.rs
The problem: vhost-device vsock failed to send "large" packet from guest to host
How to fix: in this context, epoll listener can be already registered via other TX event, so let it try epoll_modify first to avoid 'silent' failure which possibly drops packets.
Fixes #494 
requirements:
test.
=> vsock: try epoll_modify before epoll_register in recv_pkt

staging/vhost-device-sound/Cargo.toml, staging/vhost-device-sound/src/audio_backends/alsa.rs, staging/vhost-device-sound/src/audio_backends/null.rs, staging/vhost-device-sound/src/audio_backends/pipewire.rs, staging/vhost-device-sound/src/device.rs, staging/vhost-device-sound/src/lib.rs, staging/vhost-device-sound/src/stream.rs
Depends on #513
Add basic lints to deny unidiomatic or potentially bad code.
requirements:
test.
=> sound: add clippy lint checks 

CODEOWNERS
Add self to CODEOWNERS to contribute with reviewing, merging other PRs and maintaining the vhost-device-sound crate.
Also remove @mathieupoirier, who is unavailable for maintainer duties at
this time.
=> CODEOWNERS: add epilys, remove mathieupoirier 

staging/vhost-device-sound/Cargo.toml
Previous commit added categories to Cargo.toml, but the only value was `multimedia::audio`.
requirements:
test.
=> sound: add `virtualization` in Cargo.toml categories [trivial]

staging/coverage_config_x86_64.json, staging/vhost-device-sound/src/device.rs
Adds tests in test_sound_thread_failure to test that process_control() returns Err() in the following four conditions:
* control request with a single descriptor
* control request in which first descriptor is write-only
* control request in which second descriptor is read-only
* control request with less than three descriptors for control requests that require three, e.g., PcmInfo, ChmapInfo
requirements:
test.
=> sound/test: add tests for device.rs

Cargo.lock, coverage_config_x86_64.json, vhost-device-vsock/Cargo.toml, vhost-device-vsock/src/main.rs, vhost-device-vsock/src/rxops.rs, vhost-device-vsock/src/rxqueue.rs, vhost-device-vsock/src/thread_backend.rs, vhost-device-vsock/src/txbuf.rs, vhost-device-vsock/src/vhu_vsock.rs, vhost-device-vsock/src/vhu_vsock_thread.rs, vhost-device-vsock/src/vsock_conn.rs
Add more tests in vhost-device-vsock to increase the coverage.
Some of them are really simple and perhaps nonsensical (tests for
Debug, Clone, etc.), but for now we don't know how to disable this
in the tool, so let's cover these cases.
The first patch is a fix of an issue I discovered while implementing the test.
The vhost-device-vsock functions coverage increases from 70.73% to
90.45%:
```
Filename             Functions  Missed Functions  Executed
----------------------------------------------------------
main.rs                     51                12    76.47%
rxops.rs                     8                 0   100.00%
rxqueue.rs                  20                 0   100.00%
thread_backend.rs           20                 3    85.00%
txbuf.rs                    17                 0 …
```
=> vsock: increase test coverage

staging/coverage_config_x86_64.json, staging/vhost-device-sound/src/virtio_sound.rs
This commit adds simple tests for the structures in virtio_sound.rs. The tests are split into two tests to fix a clippy error regarding the cognitive complexity when I have used a single test to cover both debug and clone.
requirements:
test.
=> sound/test: add tests for virtio_sound.rs

vhost-device-vsock/src/main.rs
`test_start_backend_servers_failure` is failing intermittently. In slow systems it can happen that one thread is exiting due to an error (in this case we expect a CidAlreadyInUse error) and another thread is creating files (Unix socket), so sometimes test_dir.close() fails because after deleting all the files it finds more. So let's discard eventual errors.
requirements:
test.
=> vsock/test: fix intermittent failures

staging/vhost-device-sound/src/audio_backends/pipewire.rs, staging/vhost-device-sound/src/audio_backends/pipewire/test_utils.rs
Add test utility to launch a temporary dbus daemon, pipewire. This is necessary to run pipewire tests under CI.
requirements:
test.
=> sound/pipewire: add test util harness for launching pipewire+dbus

Cargo.lock, staging/Cargo.lock, staging/vhost-device-sound/Cargo.toml, staging/vhost-device-sound/src/device.rs, staging/vhost-device-video/Cargo.toml, staging/vhost-device-video/src/vhu_video.rs, staging/vhost-device-video/src/vhu_video_thread.rs, vhost-device-gpio/Cargo.toml, vhost-device-gpio/src/vhu_gpio.rs, vhost-device-i2c/Cargo.toml, vhost-device-i2c/src/vhu_i2c.rs, vhost-device-rng/Cargo.toml, vhost-device-rng/src/vhu_rng.rs, vhost-device-scmi/Cargo.toml, vhost-device-scmi/src/vhu_scmi.rs, vhost-device-scsi/Cargo.toml, vhost-device-scsi/src/vhu_scsi.rs, vhost-device-vsock/Cargo.toml, vhost-device-vsock/src/vhu_vsock.rs, vhost-device-vsock/src/vhu_vsock_thread.rs, vhost-device-vsock/src/vsock_conn.rs
- features were renamed from slave -> backend
- generics got simplified
Draft until the version is actually released
requirements:
test.
=> Update vhost-user-backend to 0.11 series

.github/dependabot.yml
We forgot to tell dependabot to also run in the "staging" nested workspace. Let's enable it.
Closes #536
=> dependabot: run it also for staging crates

staging/vhost-device-sound/src/lib.rs, staging/vhost-device-video/src/main.rs, vhost-device-gpio/src/backend.rs, vhost-device-i2c/src/main.rs, vhost-device-rng/src/main.rs, vhost-device-scmi/src/main.rs, vhost-device-scsi/src/main.rs, vhost-device-vsock/src/main.rs
~**Depends on https://github.com/rust-vmm/vhost/pull/173**~
This cleans up a couple of error reporting related issues and introduces use
of the proposed `serve` API [1].
[1] https://github.com/rust-vmm/vhost/pull/173
requirements:
test.
=> Refactoring around daemon launch

staging/vhost-device-sound/src/device.rs, staging/vhost-device-video/src/vhu_video_thread.rs, vhost-device-i2c/src/vhu_i2c.rs, vhost-device-rng/src/vhu_rng.rs, vhost-device-scmi/src/vhu_scmi.rs, vhost-device-vsock/src/vhu_vsock_thread.rs
Since everyone copied the first bits of code from the I2C crate, the same issue is present almost everywhere. The returned value isn't checked at all by the callers. Stop returning bool unnecessarily.
=> vhost-device: Don't return bool unnecessarily

Cargo.lock, Cargo.toml, README.md, coverage_config_x86_64.json, vhost-device-template/CHANGELOG.md, vhost-device-template/Cargo.toml, vhost-device-template/LICENSE-APACHE, vhost-device-template/LICENSE-BSD-3-Clause, vhost-device-template/README.md, vhost-device-template/src/main.rs, vhost-device-template/src/vhu_foo.rs
This adds a basic template crate, which will be useful for new developers to understand how things work and layout all basic stuff they are expected to write to make it work.
The current implementation just parses all the requests from the virtqueue and prints the number of descriptor chains and size of each descriptor buffer in there.
This adds basic sanity tests as well for the same, which can be run to test the working of the crate.
=> Add vhost-device-template crate

staging/vhost-device-sound/src/audio_backends/alsa.rs, staging/vhost-device-sound/src/audio_backends/pipewire.rs, staging/vhost-device-sound/src/lib.rs, staging/vhost-device-sound/src/stream.rs
This PR is the result of splitting https://github.com/rust-vmm/vhost-device/pull/556. This PR addresses the required changes to remove the runner thread in the ALSA backend. Also, it propagates the errors from the audio backed  to the device. Finally, this PR prepares the ALSA backend to get rid of the Control Message in a following PR.
requirements:
test.
=> Remove runner thread in alsa

vhost-device-scmi/src/main.rs, vhost-device-scmi/src/vhu_scmi.rs
clap can parse a PathBuf directly from the command line arguments, and paths are not always UTF-8. Use PathBuf instead of a String to allow for all valid filesystem paths.
requirements:
test.
=> scmi: use PathBuf for socket path

vhost-device-scmi/src/devices/common.rs, vhost-device-scmi/src/main.rs
~~Depends on PR #571~~
Use clap's derive attributes to print device help instead of doing it
manually with the parsed arguments.
```text
Usage: vhost-device-scmi [OPTIONS]
Options:
-s, --socket-path <SOCKET_PATH>  vhost-user socket to use (required)
-d, --device <DEVICE>...         Devices to expose
--help-devices               Print help on available devices
-h, --help                       Print help
```
```text
vhost-user SCMI backend device
Usage: vhost-device-scmi [OPTIONS] --socket-path <SOCKET_PATH>
Options:
-s, --socket-path <SOCKET_PATH>  vhost-user socket to use
-d, --device <DEVICE>...         Devices to expose
-h, --help                       Print help
-V, --version                    Print version
Available devices:
- iio: industrial I/O sensor
Parameters:
- path: path to …
```
=> scmi: make socket_path required

staging/vhost-device-sound/src/audio_backends/pipewire.rs
The threadloop has to be stopped only when the audio backend is dropped otherwise `release()` stops it and it is not started again. The threadloop must be active all alone the life of the audio backend. The fix proposed at #555 seems working only because, during the tests, the pw backend is instantiated each time after `release()` but if `start()` is issued after `release()`, the pw backend stops to work. This issue has been resolved with current commit.  
requirements:
test.
=> sound/pipewire: stop threadloop during drop

vhost-device-scmi/src/main.rs
Commit b37e7e5709b44ddce52df6b0ec8b8feb0d7a92e1 changed how the --help-devices text output was used inadvertently by including it by default in the help output. Restore the --help-devices argument and make it exclusive: you cannot combine it with other arguments. This way, socket_path does not have to be an Option<PathBuf>.
Cc @mz-pdm 
requirements:
test.
=> scmi: revert to previous --help-devices behavior

Cargo.toml, README.md, vhost-device-input/CHANGELOG.md, vhost-device-input/Cargo.toml, vhost-device-input/LICENSE-APACHE, vhost-device-input/LICENSE-BSD-3-Clause, vhost-device-input/README.md, vhost-device-input/src/input.rs, vhost-device-input/src/main.rs, vhost-device-input/src/vhu_input.rs
This patch set is to add vhost backend for emulation input device.
requirements:
test.
=> Add support for vhost device input v1

staging/vhost-device-sound/src/audio_backends.rs, staging/vhost-device-sound/src/audio_backends/alsa.rs, staging/vhost-device-sound/src/audio_backends/pipewire.rs, staging/vhost-device-sound/src/device.rs, staging/vhost-device-sound/src/lib.rs
This PR is the result of splitting https://github.com/rust-vmm/vhost-device/pull/556. This PR addresses the required changes to remove the `ControlMessage` parameter from the `set_param()` and `release()` functions. In particular in `set_param()`, this PR replaces it with the `VirtioSndPcmSetParams` structure that is parsed in the device thus preventing the audio backend to manipulate descriptors. 
Thanks for reviewing!
requirements:
test.
=> sound: remove ctrl msg param

staging/coverage_config_x86_64.json, staging/vhost-device-sound/src/audio_backends.rs, staging/vhost-device-sound/src/audio_backends/alsa.rs, staging/vhost-device-sound/src/audio_backends/alsa/test_utils.rs, staging/vhost-device-sound/src/audio_backends/null.rs, staging/vhost-device-sound/src/audio_backends/pipewire.rs, staging/vhost-device-sound/src/device.rs, staging/vhost-device-sound/src/lib.rs, staging/vhost-device-sound/src/main.rs, staging/vhost-device-sound/src/virtio_sound.rs
add tests to Alsa and other test stuff
<table><tbody><tr><td class="column-entry-bold">Filename</td><td class="column-entry-bold">Function Coverage</td><td class="column-entry-bold">Line Coverage</td><td class="column-entry-bold">Region Coverage</td><td class="column-entry-bold">Branch Coverage</td></tr><tr class="light-row"><td><span><a >audio_backends.rs</a></span></td><td class="column-entry-green"><span> 100.00% (6/6)</span></td><td class="column-entry-yellow"><span>  92.00% (23/25)</span></td><td class="column-entry-red"><span>  75.00% (9/12)</span></td><td class="column-entry-red"><span>- (0/0)</span></td></tr><tr class="light-row"><td><span><a >audio_backends/alsa.rs</a></span></td><td class="column-entry-red"><span>   0.00% (0/21)</span></td><td class="column-entry-red"><span> …
=> sound: add tests to Alsa and other test stuff

Cargo.lock
$ cargo audit -q --deny warnings
Crate:     unsafe-libyaml
Version:   0.2.9
Warning:   unsound
Title:     Unaligned write of u64 on 32-bit and 16-bit platforms
Date:      2023-12-20
ID:        RUSTSEC-2023-0075
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0075
Dependency tree:
unsafe-libyaml 0.2.9
└── serde_yaml 0.9.27
└── vhost-device-vsock 0.1.0
error: 1 denied warning found!
=> vhost-device-vsock: update serde_yaml dependency

staging/vhost-device-sound/Cargo.toml, staging/vhost-device-sound/src/audio_backends.rs, staging/vhost-device-sound/src/lib.rs, staging/vhost-device-sound/src/main.rs
Disable builds for musl, where alsa-sys and pipewire build fail on rust-vmm-container due to missing tools and headers.
requirements:
test.
=> sound: skip musl builds

Cargo.lock
$ cargo audit -q --deny warnings
Crate:     shlex
Version:   1.2.0
Title:     Multiple issues involving quote API
Date:      2024-01-21
ID:        RUSTSEC-2024-0006
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0006
Solution:  Upgrade to >=1.3.0
Dependency tree:
shlex 1.2.0
├── bindgen 0.66.1
│   ├── pipewire-sys 0.7.2
│   │   └── pipewire 0.7.2
│   │       └── vhost-device-sound 0.1.0
│   └── libspa-sys 0.7.2
│       ├── pipewire-sys 0.7.2
│       ├── pipewire 0.7.2
│       └── libspa 0.7.2
│           └── pipewire 0.7.2
└── bindgen 0.63.0
└── libgpiod-sys 0.1.1
└── libgpiod 0.2.1
└── vhost-device-gpio 0.1.0
=> build(deps): bump shlex dependency

Cargo.lock, vhost-device-sound/Cargo.toml, vhost-device-sound/src/audio_backends/pipewire.rs
Update pipewire dependencies after the MR -
https://gitlab.freedesktop.org/pipewire/pipewire-rs/-/merge_requests/210
in pipewire-rs that fixes the crash during vhost-device-sound
test execution
requirements:
test.
=> vhost-device-sound: update pipewire dependencies

vhost-device-sound/src/audio_backends/pipewire.rs
*add set_position() callback to specify audio channels position*
requirements:
test.
=> sound/pipewire: specify audio channel position

vhost-device-i2c/README.md, vhost-device-i2c/src/i2c.rs, vhost-device-i2c/src/main.rs
When the adapter name is used as a parameter, some adapters share the same name. For instance, both /dev/i2c-0 and /dev/i2c-1 have the bus name "xxxx". This leads to only the first found I2C adapter being opened.
To increase flexibility, accept both the I2C master's name and number as parameters and parse accordingly.
In some scenarios, serveral i2c adapters share the same bus-name, which results in only the first founded i2c adapter being
opened.
To address this issue, introduced support for identification by names or numbers, providing users with a choice.
requirements:
test.
Release" …
=> i2c: Support for both bus name and bus number

vhost-device-sound/src/audio_backends/pipewire.rs
For capturing, pipewire backend is incrementing the position in the buffer, however, this is already done by write_input() thus resulting in incrementing two times the position. This commit removes the incrementation that happens in pipewire.
requirements:
test.
=> sound/pipewire: remove duplicate increment

Cargo.lock, Cargo.toml
In vhost-device-vsock we use the `config` crate which now has the `yaml-rust` dependency that is unmaintained as cargo audit is reporting. See https://github.com/rust-vmm/vhost-device/issues/639
They merged the fix, but for now they don't do a release because they don't have a maintainer. To get the CI green, let's do this workaround, but before the next release we have to find a solution.
=> Use a patched version for the `config` dependency

vhost-device-sound/src/audio_backends/pipewire.rs, vhost-device-sound/src/stream.rs
The PCM command transition prepare->prepare or set_param->prepare is allowed by the specification. however this type of transition in pipewire lead to multiple creation of pipewire streams that are not destroyed. This PR ensures that in a case like this, when the prepare fn() in the pipewire backend is called multiple times without the release fn(), there should be only one pipewire stream.
Close #490
requirements:
test.
=> sound/pipewire: destroy multiple pipewire streams that are not destroyed

vhost-device-vsock/README.md
In the examples we used hugepages, which could be useful in special cases where the performance matters, but this requires specific configuration and permissions to allocate them.
Let's simplify the examples by using memfd, removing `--mem-prealloc`, and the superfluous `-m 512M`.
requirements:
test.
=> vsock/README: simplify the examples using memfd

vhost-device-vsock/README.md, vhost-device-vsock/src/main.rs, vhost-device-vsock/src/thread_backend.rs, vhost-device-vsock/src/vhu_vsock.rs
When running "vhost-device-vsock" against QEMU's "vhost-user-vsock-device" (i.e., mmio version, not the pci one) causes an error output on the vhost-device-vsock terminal:
```
[2024-06-30T10:57:54Z ERROR vhost_device_vsock] Fatal error: failed to handle request: invalid parameters 
```
And some errors on the QEMU terminal too like below:
```
qemu-system-x86_64: Failed to read msg header. Read -1 instead of 12.
Original request 1.
qemu-system-x86_64: Failed to write msg. Wrote -1 instead of 20.
qemu-system-x86_64: vhost VQ 1 ring restore failed: -22: Invalid argument (22)
qemu-system-x86_64: Failed to set msg fds.
qemu-system-x86_64: vhost VQ 0 ring restore failed: -22: Invalid argument (22)
qemu-system-x86_64: Error starting …
```
=> vhost-device-vsock: increase max queue size to 1024

coverage_config_x86_64.json, vhost-device-sound/src/audio_backends/alsa.rs, vhost-device-sound/src/audio_backends/null.rs, vhost-device-sound/src/audio_backends/pipewire.rs, vhost-device-sound/src/device.rs, vhost-device-sound/src/lib.rs, vhost-device-sound/src/stream.rs, vhost-device-sound/src/virtio_sound.rs
This commit makes `device.rs` to use `descriptor_utils.rs` API to read/write requests independent of the descriptor distribution. This is a draft PR in which I am still working on.
Thanks for the comments.
requirements:
test.
=> sound: use descriptor_utils.rs to manipulate requests

Cargo.lock, vhost-device-scmi/CHANGELOG.md, vhost-device-scmi/Cargo.toml
Update CHANGELOG.md and Cargo.toml for v0.2.0 relase.
=> scmi: Prepare v0.2.0 release

vhost-device-scmi/CHANGELOG.md, vhost-device-scmi/src/devices/common.rs
SensorT methods invalid_property and process_property are unused and the compiler complains about the fact.
SensorT methods invalid_property and process_property are unused and
the compiler complains about the fact.
Fixes: #694
=> scmi: Remove an unused piece of code

Cargo.lock, Cargo.toml, README.md, coverage_config_x86_64.json, vhost-device-spi/CHANGELOG.md, vhost-device-spi/Cargo.toml, vhost-device-spi/LICENSE-APACHE, vhost-device-spi/LICENSE-BSD-3-Clause, vhost-device-spi/README.md, vhost-device-spi/src/linux_spi.rs, vhost-device-spi/src/main.rs, vhost-device-spi/src/spi.rs, vhost-device-spi/src/vhu_spi.rs, vhost-device-spi/src/virtio_spi.rs
This program is a vhost-user backend that emulates a VirtIO SPI bus. This program takes the layout of the spi bus and its devices on the host OS and then talks to them via the /dev/spidevX.Y interface when a request comes from the guest OS for a SPI device.
The implementation corresponds with the specification: https://github.com/oasis-tcs/virtio-spec/tree/virtio-1.4/device-types/spi
requirements:
test.
=> vhost-device-spi: Add initial implementation

Cargo.lock
Cargo audit complains about yanked version of `bytemuck`:
Crate:     bytemuck
Version:   1.16.1
Warning:   yanked
Dependency tree:
bytemuck 1.16.1
└── atomic 0.6.0
└── figment 0.10.19
└── vhost-device-vsock 0.2.0
requirements:
test.
=> Cargo.lock: update bytemuck to 1.16.3

README.md, staging/Cargo.toml, staging/coverage_config_x86_64.json, staging/vhost-device-can/CHANGELOG.md, staging/vhost-device-can/Cargo.toml, staging/vhost-device-can/LICENSE-APACHE, staging/vhost-device-can/LICENSE-BSD-3-Clause, staging/vhost-device-can/README.md, staging/vhost-device-can/src/backend.rs, staging/vhost-device-can/src/can.rs, staging/vhost-device-can/src/main.rs, staging/vhost-device-can/src/vhu_can.rs, staging/vhost-device-can/src/virtio_can.rs
This PR introduces an initial implementation of vhost-device-can device.
The development of this device was performed by Virtual Open Systems in the context
of the [Automotive Grade Linux](https://www.automotivelinux.org/) SDV-EG (Software Defined Vehicle expert group)
AGL Native VIRTIO project. Part of this effort has already been upstreamed
(see [AGL Gerrit can patch](https://gerrit.automotivelinux.org/gerrit/c/AGL/meta-agl-devel/+/29407)).
The new device takes as arguments two CAN/FD interfaces ("can_out", "can_in")
and forward the traffic between those, and virtio-can driver ([virtio-can RFC](https://lwn.net/Articles/934187/)).
Since there is no upstream implementation of any vhost-user-can frontend in QEMU,
the current version has only been tested with virtio-loopback design. …
=> vhost-device-can: Add initial implementation

Cargo.lock, vhost-device-vsock/CHANGELOG.md, vhost-device-vsock/Cargo.toml, vhost-device-vsock/README.md, vhost-device-vsock/src/main.rs, vhost-device-vsock/src/thread_backend.rs, vhost-device-vsock/src/vhu_vsock.rs, vhost-device-vsock/src/vhu_vsock_thread.rs, vhost-device-vsock/src/vsock_conn.rs
Hi. I have been working on adding [AWS Nitro Enclave](https://docs.aws.amazon.com/enclaves/latest/user/nitro-enclave.html) emulation support in QEMU. Nitro enclave VMs are spawned from EC2 VMs and the enclave VMs always see the parent VM as CID 3 and the applications in the enclave VM talk to the parent VM using AF_VSOCK to CID 3. More details about this are in the [cover letter](https://mail.gnu.org/archive/html/qemu-devel/2024-08/msg01594.html) for the patch posted in qemu-devel.
From the QEMU side, it would be cumbersome to run a separate VM with CID 3 with the necessary applications while running a nitro-enclave VM. So there was some discussion in the virtualization mailing list about how we could make the UX simpler for users without requiring to run  a separate VM with CID 3 and …
=> Support proxying using vsock

Cargo.lock
`cargo audit` warned about a yanked version of once_cell we are using:
Crate:     once_cell
Version:   1.20.0
Warning:   yanked
Dependency tree:
once_cell 1.20.0
├── which 4.4.2
│   └── bindgen 0.63.0
│       └── libgpiod-sys 0.1.1
│           └── libgpiod 0.2.1
│               └── vhost-device-gpio 0.1.0
├── tempfile 3.12.0
│   ├── vhost-device-vsock 0.2.0
│   ├── vhost-device-sound 0.2.0
│   ├── vhost-device-scsi 0.1.0
│   ├── vhost-device-rng 0.1.0
│   └── vhost-device-input 0.1.0
└── pipewire 0.8.0
└── vhost-device-sound 0.2.0
=> Cargo.lock: downgrade once_cell from 1.20.0 to 1.19.0

vhost-device-scmi/src/devices/common.rs, vhost-device-scmi/src/devices/fake.rs, vhost-device-scmi/src/devices/iio.rs, vhost-device-scmi/src/main.rs, vhost-device-scmi/src/scmi.rs, vhost-device-scmi/src/vhu_scmi.rs
This is Samsung Team. We want to contribute scmi notification implement.
In virtio-spec, if feature VIRTIO_SCMI_F_P2A_CHANNELS was negotiated, device should implement SCMI notification.
In our embeded environment, we enable iio sensor with notification feature, and configure this feature.
=> Vhost device scmi notification implement

Cargo.lock, vhost-device-scmi/CHANGELOG.md, vhost-device-scmi/Cargo.toml
Update CHANGELOG.md and Cargo.toml for v0.3.0 release. This release adds SCMI notification support.
Let's make with a new release of vhost-device-scmi, with SCMI notification support.
requirements:
- [ x] All commits in this PR have Signed-Off-By trailers (with
- [ x] All added/changed functionality has a corresponding unit/integration
test.
- [ x] All added/changed public-facing functionality has entries in the "Upcoming 
- [ x] Any newly added `unsafe` code is properly documented.
=> scmi: Prepare v0.3.0 release

vhost-device-vsock/src/main.rs, vhost-device-vsock/src/thread_backend.rs, vhost-device-vsock/src/vhu_vsock.rs, vhost-device-vsock/src/vhu_vsock_thread.rs
This reverts commit cec57c943354e938cde08ba984f8b1efb6cfa99a.
Thanks to https://github.com/rust-vmm/rust-vmm-ci/pull/165 our CI is now able to use AF_VSOCK, so let's force the tests to run to discover any problems in the future.
Thanks to @roypat for the help on debugging and finding the solution :-)
=> Revert "vsock: Skip tests causing CI failure"

vhost-device-vsock/CHANGELOG.md, vhost-device-vsock/src/vhu_vsock.rs
As per the vhost-user specification:
"Back-ends should always implement the VHOST_USER_PROTOCOL_F_MQ protocol feature, even for devices with a fixed number of virtqueues, since it is simple to implement and offers a degree of introspection."
Vsock backend support three virtqueues and hence this should be set.
requirements:
test.
=> vsock: Set VhostUserProtocolFeatures::MQ

.github/dependabot.yml
We have missused `exclude-patterns` and `applies-to` in previous setup, they are documented in [1]:
- `exclude-patterns`: Use to exclude certain dependencies from the group. If a dependency is excluded from a group, Dependabot will continue to **raise single pull requests** to update the dependency to its latest version.
- `applies-to`: Use to specify whether the rules in the group apply to version updates or security updates. applies-to can be version-updates or security-updates.
Options in `groups` section is a matter of grouping strategy of these detected udpates.
All in all, to effectively "group" these updates, we need to use `allow` and `ignore` to specify update "candidates" for dependabot, if the "candidates" were duplicated in the first place, no matter the grouping strategy, the …
=> dependabot: Group updates to reduce noise

staging/Cargo.lock, staging/Cargo.toml, staging/coverage_config_x86_64.json, staging/vhost-device-gpu/CHANGELOG.md, staging/vhost-device-gpu/Cargo.toml, staging/vhost-device-gpu/LICENSE-APACHE, staging/vhost-device-gpu/LICENSE-BSD-3-Clause, staging/vhost-device-gpu/README.md, staging/vhost-device-gpu/rustfmt.toml, staging/vhost-device-gpu/src/device.rs, staging/vhost-device-gpu/src/lib.rs, staging/vhost-device-gpu/src/main.rs, staging/vhost-device-gpu/src/protocol.rs, staging/vhost-device-gpu/src/virtio_gpu.rs
I and @mtjhrc have been working on this PR that adds a new crate - vhost-device-gpu.
This vhost-device-gpu crate provides a vhost-user backend daemon for VIRTIO GPU device emulation as specified in the 
[VIRTIO Spec v.1.2](
https://docs.oasis-open.org/virtio/virtio/v1.2/csd01/virtio-v1.2-csd01.html#x1-3650007)
~~This crate utilizes the rutabaga crate Imported from crosvm commit: 02110bc6fcc6af70329f410aef8859ec70dd9224
rutabaga_gfx: fixes for crrev.com/c/5279413~~
~~The rutabaga crate is vendored because it contains minor modifications to rutabaga_gfx to make it compatible with vhost-device-gpu eventually we would  use the upstream version when things are more stable.~~
This crate utilizes the rutabaga crate v0.1.4 specifically the virglrenderer and gfxstream features.
This crate includes …
=> vhost-device-gpu: Add Initial Implementation

vhost-device-input/CHANGELOG.md
It seems that we haven't tagged a release since vhost-device-input PR was merged.
Let's now release the first version: v0.1.0
Closes: #780
=> vhost-device-input: prepare release v0.1.0

staging/vhost-device-gpu/Cargo.toml, staging/vhost-device-gpu/README.md, staging/vhost-device-gpu/src/lib.rs, staging/vhost-device-gpu/src/protocol.rs, staging/vhost-device-gpu/src/virtio_gpu.rs
Add a new compile-time feature, `gfxstream`, which is included in the
default features. The only thing that changes is that we can now build
without requiring `gfxstream_backend` on compilation time, which helps
in cases it is not packaged in a distro, or is not available at a user's
build machine.
Also update `README.md` with information about the build-time feature,
and do a light reformatting while at it.
CC @dorindabassey @mtjhrc if you want to take a look
=> gpu: guard gfxstream dependency with a feature

vhost-device-scmi/src/devices/common.rs, vhost-device-scmi/src/scmi.rs
clippy 0.1.83 (90b35a6 2024-11-26) emits a new warning about manual arithmetic check and rustc 1.83.0 (90b35a623 2024-11-26) emits 2 new warnings about elided lifetime has a name.
requirements:
test.
=> scmi: fix new clippy/rustc warnings

vhost-device-sound/src/audio_backends/alsa.rs, vhost-device-sound/src/audio_backends/alsa/test_utils.rs, vhost-device-sound/src/audio_backends/null.rs, vhost-device-sound/src/audio_backends/pipewire.rs, vhost-device-sound/src/device.rs, vhost-device-sound/src/stream.rs
Instead of using unsafe {} and undefined behavior (mutable shared static
references) use LazyLock which initializes the harness on first
dereference and provides immutable access only (the harness type has
interior mutability).
=> sound: Put AlsaTestHarness static in a LazyLock

Cargo.lock, vhost-device-sound/Cargo.toml, vhost-device-sound/src/audio_backends.rs, vhost-device-sound/src/audio_backends/alsa.rs, vhost-device-sound/src/audio_backends/pipewire.rs, vhost-device-sound/src/audio_backends/pipewire/test_utils.rs, vhost-device-sound/src/lib.rs
Sometimes pw backend creation on CI fails with errors like for example:
thread 'audio_backends::pipewire::tests::test_pipewire_backend_invalid_stream' panicked at vhost-device-sound/src/audio_backends/pipewire.rs:98:42:
Failed to connect to core: CreationFailed
Add a simple kind of truncated exponential backoff retry wrapper to
PwBackend::new().
Also, run all tests that modify their process environment under a fork using the `rusty_fork` crate.
Depends on #788 which fixes lint warnings
=> sound/pipewire: add truncated exp backoff to tests and fork them

staging/vhost-device-video/src/vhu_video.rs, vhost-device-gpio/src/virtio_gpio.rs, vhost-device-i2c/src/i2c.rs, vhost-device-i2c/src/vhu_i2c.rs, vhost-device-vsock/src/vhu_vsock.rs
Fix new warn by default clippy lint, empty_line_after_doc_comments, by removing empty lines after doc comments.
requirements:
test.
=> Fix clippy::empty_line_after_doc_comments

vhost-device-scmi/CHANGELOG.md, vhost-device-scmi/src/devices/common.rs, vhost-device-scmi/src/devices/iio.rs, vhost-device-scmi/src/scmi.rs
For Android requirment, virtio-scmi axis descriptor should support extended attributes. This patch does this things.
We get axis's resolution during reading "scale" and store. When agent wants to get axis description,
it will add to extend attribute field.
At the same time, max and min range have also been configured.
And because of supporting extended attributes, in flow of handle command SENSOR_ AXIS_DESCRIPTION_GET, it should report frontend the axis info one by one instead of together, for reason that it will exceed the size of descriptor buffer size.
Change-Id: Idc1984c6e23846cb877644a4459dbf6b6fbd63fa
This patch extends the attributes of scmi sensor which is required by Android Trout.
=> scmi: extended sensor attributes support

vhost-device-vsock/CHANGELOG.md, vhost-device-vsock/src/vhu_vsock_thread.rs, vhost-device-vsock/src/vsock_conn.rs
Currently the vsock connection always triggers on EPOLLOUT. When a host applicationlistens to the UDS, it's almost always writable, and thus keeps triggering backend events with EPOLLOUT on the connection. As a result, vhost-device-vsock daemon consumes 100% CPU.
To make it more CPU efficient, it can instead unsubscribe EPOLLOUT whenever there is no more data to send. It can re-subscribe if the connection cannot write out all bytes. This change causes the CPU util to drop to negligible level.
requirements:
test.
=> Disable EPOLLOUT if triggered while txbuf is empty

vhost-device-sound/src/audio_backends/pipewire/test_utils.rs
clippy warns:
```
error: this `map_or` is redundant
--> vhost-device-sound/src/audio_backends/pipewire/test_utils.rs:210:12
|
210 |         if max_retries.map_or(false, |max| iterations >= max) {
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use is_some_and instead: `max_retries.is_some_and(|max| iterations >= max)`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
```
=> sound: fix clippy::unnecessary_map_or lint

vhost-device-sound/CHANGELOG.md, vhost-device-sound/src/device.rs, vhost-device-sound/src/virtio_sound.rs
This commit introduces a new controls field in VirtioSoundConfig to represent the total number of available control elements. It's based on the recent changes to the virtio-snd header file in QEMU. Fixes this issue:
https://gitlab.com/qemu-project/qemu/-/issues/2805
requirements:
test.
=> vhost-device-sound: Add controls field in VirtioSoundConfig

vhost-device-console/README.md
In the example of using `vhost-user-console-pci`, the id should be
`con0` instead of `con`.
requirements:
test.
=> vhost-device-console: Fix a typo in README

.buildkite/README.md, .buildkite/main-tests.json
`vhost-device-gpu` has dependencies that do not work well on musl. Also `vhost-device-gpio` has the same problem, but we merged workarounds.
Instead of continuing to make hacks to compile empty main for these applications. Better to have our own pipeline also for the main workspace. In that way we can easily exclude applications (e.g. that do not support musl) as discussed in
https://github.com/rust-vmm/vhost-device/pull/801
The new `.buildkite/main-tests.json` file is copied from rust-vmm-ci/.buildkite/test_description.json from commit 09aef99 ("chore: update container version to v48")
=> buildkite: add main-tests.json

vhost-device-console/CHANGELOG.md, vhost-device-console/README.md, vhost-device-console/src/backend.rs, vhost-device-console/src/main.rs, vhost-device-console/src/vhu_console.rs
Some hypervisors, e.g. UML (User-Mode Linux), negotiate a queue size larger 
than `QUEUE_SIZE` (128), which results in failures (see below). This patch 
allows users to specify it using `--max-queue-size <size>`.
```
[2025-02-11T10:21:51Z ERROR vhost_device_console] Fatal error: failed to handle request: invalid parameters
```
requirements:
test.
=> vhost-device-console: Being able to specify max queue size

vhost-device-vsock/src/main.rs, vhost-device-vsock/src/thread_backend.rs, vhost-device-vsock/src/vhu_vsock.rs, vhost-device-vsock/src/vhu_vsock_thread.rs
This PR changes socket paths type from String to PathBuf in vhost-user-vsock. 
This work was started in #446 but never completed.
requirements:
test.
=> vsock: Use PathBuf for socket paths instead of Strings

vhost-device-gpio/src/backend.rs, vhost-device-sound/src/device.rs, vhost-device-sound/src/lib.rs, vhost-device-sound/src/main.rs
This PR changes socket paths type from String to PathBuf in vhost-user-gpio and vhost-user-sound.
This work was started in #446 and but never completed.
This PR along with #819 should complete the work.
requirements:
test.
=> gpio, sound: Use PathBuf for socket paths instead of Strings

vhost-device-can/src/main.rs, vhost-device-can/src/vhu_can.rs, vhost-device-console/src/vhu_console.rs, vhost-device-gpio/src/vhu_gpio.rs, vhost-device-gpu/src/device.rs, vhost-device-i2c/src/vhu_i2c.rs, vhost-device-input/src/vhu_input.rs, vhost-device-rng/src/vhu_rng.rs, vhost-device-scmi/src/devices/common.rs, vhost-device-scmi/src/scmi.rs, vhost-device-scmi/src/vhu_scmi.rs, vhost-device-scsi/src/vhu_scsi.rs, vhost-device-scsi/src/virtio.rs, vhost-device-sound/src/device.rs, vhost-device-sound/src/lib.rs, vhost-device-spi/src/spi.rs, vhost-device-spi/src/vhu_spi.rs, vhost-device-template/src/vhu_foo.rs, vhost-device-vsock/src/vhu_vsock.rs
Fix clippy warnings reported by clippy 0.1.85 (4d91de4e48 2025-02-17).
requirements:
test.
=> clippy: Fix clippy warnings found in rust toolchain v1.85.0

.cargo/config.toml, Cargo.lock, Cargo.toml, README.md, coverage_config_x86_64.json, vhost-device-scmi/README.md, vhost-device-scmi/src/args.rs, vhost-device-scmi/src/main.rs, vhost-device-sound/src/args.rs, vhost-device-sound/src/lib.rs, vhost-device-sound/src/main.rs, xtask/Cargo.toml, xtask/README.md, xtask/build.rs, xtask/src/main.rs
For information about the cargo xtask workflow pattern see: <https://github.com/matklad/cargo-xtask>
This PR adds an `xtask` crate with only one task, `mangen`, which generates a ROFF manual page under `target/dist/man` directory for the `vhost-device-sound` and `vhost-device-scmi` binaries.
The manual pages are placed in `target/dist/man/vhost-device-sound.1` and `target/dist/man/vhost-device-scmi.1`.
Future support for other crates in this repository is possible and provisioned for.
Fixes #687
Fixes #697 
Generate the manpages:
```session
$ cargo xtask mangen
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.04s
Running `target/debug/xtask mangen`
Generated the following manual pages:
/path/to/rust-vmm/vhost-device/target/dist/man/vhost-device-sound.1 …
```
=> Add xtask to generate manpages

vhost-device-scsi/Cargo.toml
Fix scsi test compilation by correcting the dev-dependency for
virtio-queue. This would happen if someone runs the tests only for this
crate, and not workspace-wide.
requirements:
test.
=> scsi: fix test compilation

README.md
Sorry I failed to notice this when I was cleaning up.
=> README.md: fix link to GPU docs

staging/vhost-device-video/src/main.rs, staging/vhost-device-video/src/vhu_video.rs, vhost-device-i2c/src/i2c.rs, vhost-device-rng/src/vhu_rng.rs, vhost-device-scmi/src/devices/common.rs, vhost-device-scmi/src/devices/iio.rs, vhost-device-spi/src/linux_spi.rs
=> Fix cargo doc for staging
