rust-vmm/vhost-device

src/i2c/Cargo.toml
src/i2c/src/main.rs
src/i2c/src/vhu_i2c.rs

vhost-user-backend repository received few updates recently, which
caused this one to break.
Update the code here to fix the breakage.

i2c: Fix breakage introduced by vhost-user-backend updates

---

CODEOWNERS
README.md

Following the discussion on Monday document the desire for the separation of concerns even if we won't be there at the start.

Add review and design notes

---

coverage_config_x86_64.json
src/i2c/src/i2c.rs

i2c: Unsafe block

---

coverage_config_x86_64.json
i2c/src/i2c.rs
i2c/src/main.rs

- Use v14 container image with Rust 1.54
Signed-off-by: Sergii Glushchenko <gsserge@amazon.com>

Manually update rust-vmm-ci

---

Cargo.lock
Cargo.toml
README.md
coverage_config_x86_64.json
rng/Cargo.toml
rng/README.md
rng/src/main.rs
rng/src/vhu_rng.rs

This 8th revision is dealing with the rate limiting issue observed by Alex on V7.  Other than line 173 in vhu_rng.rs, no other changes have been made.

RNG: Initial vhost-device RNG implementation (v8)

---

Cargo.lock
gpio/src/gpio.rs

libgpiod received few updates, migrate to that.

gpio: Update to a newer version of libgpiod

---

gpio/Cargo.toml
i2c/Cargo.toml
rng/Cargo.toml

Signed-off-by: Obei Sideg <obei.sideg@gmail.com>
Upgrade to 2021 edition
requirements:
test.

Upgrade to 2021 edition

---

.cargo/audit.toml

Suggested here:
https://github.com/rust-vmm/rust-vmm-ci/issues/114

Ignore advisory: RUSTSEC-2021-0145

---

crates/vsock/README.md

As pointed out in https://gitlab.com/qemu-project/qemu/-/issues/1337 `-numa` is not supported by all machine types, so let's update the example using the `memory-backend` machine property.
Since we are modifying the example, let's clean up a little bit, for example by removing `-enable-kvm` and using machine properties to enable acceleration.
Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>

vsock/README: update qemu example

---

Cargo.lock
crates/gpio/src/gpio.rs

Update the version of libgpiod crates.

Cargo.lock: Update version of libgpiod

---

crates/vsock/src/main.rs
crates/vsock/src/vhu_vsock.rs
crates/vsock/src/vhu_vsock_thread.rs

vsock: Implement VhostUserBackend instead of VhostUserBackendMut for VhostUserVsockBackend

---

crates/vsock/README.md

docs: fix the wrong file link in vsock README.md

---

Cargo.lock
crates/gpio/Cargo.toml

This simplifies the packaging and allows using existing tooling to manage further updates.
The lock file was updated with:
cargo update -p libgpiod --aggressive
requirements:
test.

gpio: use libgpiod from crates.io

---

README.md

gpio: update instructions for setting up libgpiod

---

Cargo.lock
crates/gpio/Cargo.toml
crates/i2c/Cargo.toml
crates/rng/Cargo.toml
crates/scsi/Cargo.toml
crates/vsock/Cargo.toml

Switch to properly released virtio-bindings and away from carrying a git dependency. Also includes a small deps update for fixing the build.
requirements:
test.

switch to released virtio-bindings

---

Cargo.lock
crates/rng/src/vhu_rng.rs
crates/scsi/ARCHITECTURE.md
crates/scsi/README.md
crates/scsi/src/main.rs
crates/scsi/src/scsi/emulation/target.rs
crates/scsi/test/README.md
crates/vsock/Cargo.toml
crates/vsock/README.md
crates/vsock/src/main.rs

This PR contains a few fixes to problems I found while preparing the v0.1.0 release.
Thanks to @Ablu and @vireshk for the help ;-)
After merging this PR we should be ready for the release.
requirements:
test.

Fixes for release v0.1.0

---

crates/vsock/README.md
crates/vsock/src/main.rs
crates/vsock/src/thread_backend.rs
crates/vsock/src/vhu_vsock.rs
crates/vsock/src/vhu_vsock_thread.rs

Restrict the VMs a given VM can communicate with by introducing VM groups. A group is simply a name assigned to the device in the configuration. A VM can communicate with another VM only if their devices are assigned the same group name.
While implementing this, I discovered that optional parameters were not being correctly handled in the yaml config file. One needed to provide all the fields (even the optional ones) in the config file otherwise the application paniced. So, I have included a fix for this too.

vsock: Add VM groups in sibling communication

---

Cargo.lock
Cargo.toml
crates/i2c/src/i2c.rs
crates/scsi/Cargo.toml
crates/vsock/Cargo.toml

Clippy warning fix & deps / rust edition / resolver updates
requirements:
test.

Dependencies updates & cleanup

---

README.md

Add the missing link to the list of backends.

scmi: Add a SCMI link to the top README

---

Cargo.lock
crates/vsock/Cargo.toml

this project uses only yaml config, so remove some of features in config to reduce deps
requirements:
- [ V ] All commits in this PR are signed (with `git commit -s`), and the commit
- [ V ] All added/changed functionality has a corresponding unit/integration
test.
- [ V ] All added/changed public-facing functionality has entries in the "Upcoming 
- [ V ] Any newly added `unsafe` code is properly documented.

[vsock] remove unused feature to reduce deps

---

staging/Cargo.lock
staging/coverage_config_x86_64.json
staging/vhost-device-sound/Cargo.toml
staging/vhost-device-sound/src/audio_backends/null.rs
staging/vhost-device-sound/src/audio_backends/pipewire.rs
staging/vhost-device-sound/src/device.rs
staging/vhost-device-sound/src/lib.rs
staging/vhost-device-sound/src/main.rs
staging/vhost-device-sound/src/stream.rs

This PR adds testing modules for the following files in order to satisfy functional testing and code coverage.
```
Filename                       Regions    Missed Regions     Cover   Functions  Missed Functions  Executed       Lines      Missed Lines     Cover    Branches   Missed Branches     Cover
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
audio_backends.rs                   12                 8    33.33%           6                 5    16.67%          25                17    32.00%           0                 0         -
audio_backends/alsa.rs             279               279     0.00%          14 …
```

staging/vhost-device-sound: add testing module for sound

---

staging/vhost-device-sound/src/audio_backends/pipewire.rs

add safety comments
requirements:
test.

sound/pipewire: add safety comments

---

staging/vhost-device-sound/src/audio_backends/alsa.rs
staging/vhost-device-sound/src/audio_backends/pipewire.rs
staging/vhost-device-sound/src/device.rs
staging/vhost-device-sound/src/lib.rs
staging/vhost-device-sound/src/stream.rs

Re-created #476
> Add an RX code path that is similar to the existing TX code in the ALSA backend.
requirements:
test.

vhost-device-sound: implement RX capture with ALSA

---

staging/vhost-device-sound/src/audio_backends/alsa.rs
staging/vhost-device-sound/src/audio_backends/pipewire.rs
staging/vhost-device-sound/src/stream.rs

instead of consume() fn, use read_output() fn which is more appropriate and in sync with the write_input() fn.
requirements:
test.

sound: Improve function definition

---

staging/vhost-device-sound/src/audio_backends/pipewire.rs

Add pipewire capture to enable capturing for pipewire backend
requirements:
test.

sound/pipewire: Add Pipewire Capture

---

staging/coverage_config_x86_64.json
staging/vhost-device-sound/src/device.rs
staging/vhost-device-sound/src/lib.rs
staging/vhost-device-sound/src/stream.rs

This PR adds test for uncovered code paths
requirements:
test.

sound: Add Test for vhost-device-sound

---

staging/vhost-device-sound/src/audio_backends.rs
staging/vhost-device-sound/src/audio_backends/alsa.rs
staging/vhost-device-sound/src/audio_backends/pipewire.rs
staging/vhost-device-sound/src/device.rs

Somehow slipped through the reviews. Thanks @MatiasVara for catching this.
requirements:
test.

sound: remove duplicate ControlMessage definitions

---

vhost-device-template/src/main.rs

clap can parse a PathBuf directly from the command line arguments, and paths are not always UTF-8. Use PathBuf instead of a String to allow for all valid paths.
requirements:
test.

template: use PathBuf for socket path

---

vhost-device-rng/src/main.rs

clap can parse a PathBuf directly from the command line arguments, and paths are not always UTF-8. Use PathBuf instead of a String to allow for all valid paths.
requirements:
test.

rng: use PathBuf for socket path

---

vhost-device-i2c/src/main.rs

clap can parse a PathBuf directly from the command line arguments, and paths are not always UTF-8. Use PathBuf instead of a String to allow for all valid filesystem paths.
requirements:
test.

i2c: use PathBuf for socket paths

---

Cargo.lock
vhost-device-sound/Cargo.toml
vhost-device-sound/src/audio_backends/pipewire.rs

*Update pipewire dependencies to version 0.8  after the release of pipewire v0.8*
requirements:
test.

vhost-device-sound: update pipewire dependencies

---

vhost-device-sound/CHANGELOG.md

sound: Update CHANGELOG.md for crates.io release

---

vhost-device-sound/Cargo.toml

sound: update authors field in Cargo.toml

---

vhost-device-i2c/src/i2c.rs

When the user selects 'bus-name' as device parameter, we need to ensure that there is only one adapter with that name. If not, the user should be notified.
Make sure there is only one adapter with that name, otherwise the user won't know exactly which adapter is being opened.
requirements:
- [x ] All commits in this PR have Signed-Off-By trailers (with
test.
- [x ] All added/changed public-facing functionality has entries in the "Upcoming 
- [x ] Any newly added `unsafe` code is properly documented.

i2c: validate the uniqueness of adapter with 'bus-name'

---

vhost-device-vsock/src/vhu_vsock_thread.rs

fixes #307
Signed-off-by: Ramyak Mehra <ramyakmehra10@gmail.com>
requirements:
test.

check if we get '\n' early while reading from socket

---

Cargo.lock
vhost-device-sound/CHANGELOG.md
vhost-device-sound/Cargo.toml

Update changelog and Cargo.toml to v0.2.0
requirements:
test.

sound: Prepare v0.2.0 release

---

Cargo.lock
Cargo.toml
vhost-device-vsock/Cargo.toml
vhost-device-vsock/src/main.rs

The config crate, which was previously used in vsock is no longer maintained. To ensure continued support and improvement, the figment crate is used as a replacement for configuration management.
Unblocks: #688
requirements:
test.

vsock: Replace the config Crate with figment

---

Cargo.lock
vhost-device-vsock/CHANGELOG.md
vhost-device-vsock/Cargo.toml

Update changelog and Cargo.toml to version 0.2.0
requirements:
test.

vsock: Prepare version 0.2.0 release

---

staging/vhost-device-video/CHANGELOG.md
vhost-device-gpio/CHANGELOG.md
vhost-device-i2c/CHANGELOG.md
vhost-device-input/CHANGELOG.md
vhost-device-rng/CHANGELOG.md
vhost-device-scmi/CHANGELOG.md
vhost-device-scsi/CHANGELOG.md
vhost-device-template/CHANGELOG.md
vhost-device-vsock/CHANGELOG.md

Resolve small differences between our changelogs and fix small problems.
requirements:
test.

chore: standardize changelogs

---

vhost-device-vsock/CHANGELOG.md
vhost-device-vsock/vhost-device-vsock.1

Add manual page in mdoc format for `vhost-device-vsock` command
requirements:
test.

vsock: add mdoc page

---

vhost-device-spi/CHANGELOG.md

Let's follow the format of other crates as we did with commit ed0f98e ("chore: standardize changelogs")

spi: fix changelog format

---

README.md

fix(README): vhost-user-frontend and vm-virtio hyperlinks

---

CODEOWNERS

Add myself to CODEOWNERS to contribute to the reviewing and merging process of PRs related to vhost-device-sound and vhost-device-gpu crate.
requirements:
test.

CODEOWNERS: add self as code owner of sound and gpu crate

---

README.md

The crate has been moved from staging to root folder. Update the README to reflect the correct link for the crate.
requirements:
test.

README.md: Update vhost-device-gpu crate README.md link

---

Cargo.lock
vhost-device-vsock/CHANGELOG.md
vhost-device-vsock/Cargo.toml

Update changelog and Cargo.toml to version 0.3.0
Closes #860
requirements:
test.

vsock: Prepare version 0.3.0 release

---

vhost-device-gpio/src/backend.rs
vhost-device-i2c/src/i2c.rs
vhost-device-i2c/src/main.rs
vhost-device-scmi/src/devices/iio.rs
vhost-device-sound/src/lib.rs
vhost-device-sound/src/stream.rs

Would be good to run this in CI!
requirements:
test.

Fix cargo doc
